version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db
    restart: unless-stopped
    networks:
        - database_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin: # https://turreta.com/blog/2020/07/31/docker-compose-yml-for-pgadmin-and-postgresql/
    image: dpage/pgadmin4:7.3
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
    - ./pgadmin-data:/pgadmin

    networks:
        - database_network
    environment:
      PGADMIN_DEFAULT_EMAIL: <your_mail_address>
      PGADMIN_DEFAULT_PASSWORD: <password>

networks:
  database_network:
        name: database_network
        internal: false
        driver: bridge